apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mini-repo-dev
nameSuffix: -dev
commonLabels:
  overlay: dev
bases:
- ../../base
configMapGenerator:
- name: configmap
  env: dev.env
